### ISSUE TITLE
Hello World Error

### ISSUE THREAD

**Issue by killsos** [zhmushan/abc#76] opened 2020-05-19 02:25 UTC
run deno run --allow-all  server.ts 

error:

TS7006: Parameter 'c' implicitly has an 'any' type.
  .get("/hello", c => {})

modify:

 .get("/hello", c:any => {})

error same

**Comment by zhmushan** [comment] 2020-05-19 04:21
Please check your deno & abc versions

**Comment by wk989898** [comment] 2020-05-19 11:08
add bracket, like `.get("/hello", (c:any) => {})` should solve this,

**Comment by wk989898** [comment] 2020-05-19 11:11
> add bracket, like `.get("/hello", (c:any) => {})` should solve this,

parentheses

**Comment by zhmushan** [comment] 2020-05-19 11:13
But I can't reproduce this error...

**Comment by wk989898** [comment] 2020-05-19 11:22
> But I can't reproduce this error...

it caused by no `Context` type exist,so give it `any` type

**Comment by zhmushan** [comment] 2020-05-19 11:27
@wk989898 see https://github.com/denoland/deno/issues/4297
If you are using deno@v1.0.0, this error will not occur.

**Comment by evandropomatti** [comment] 2020-05-20 02:00
I can confirm that adding brackets `( )` solved it for me.

```typescript
import { Application } from "https://deno.land/x/abc/mod.ts";

const app = new Application();

app
  .get("/hello", (c) => {
    return "Hello, Abc!";
  })
  .start({ port: 8080 });
```

**Comment by cindRoberta** [comment] 2020-05-20 05:08
```typescript
import { Application } from "https://deno.land/x/abc/mod.ts";

const app = new Application();

app
  .get("/hello", (c) => { return "Hello, Abc!"; })
  .start({ port: 8080 });
```

___

[notecomm@localhost webframeworks]$ deno run --allow-net server.ts

Compile file:///home/notecomm/pdeno/webframeworks/server.ts

error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    read(_: Uint8Array): Promise<number | Deno.EOF> {
                                               ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:10:48

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Promise.resolve(Deno.EOF);
                                  ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:11:35

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async function read(buf: Uint8Array): Promise<number | Deno.EOF> {
                                                              ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:19:63

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (finished) return Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:20:31

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    let result: number | Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:21:31

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (result !== Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:29:25

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async function read(buf: Uint8Array): Promise<number | Deno.EOF> {
                                                              ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:46:63

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (finished) return Deno.EOF;
                              ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:47:31

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if ((await tp.readLine()) === Deno.EOF) {
                                           ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:59:44

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (line === Deno.EOF) throw new Deno.errors.UnexpectedEof();
                      ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:66:23

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:76:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:81:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if (eof === Deno.EOF) {
                         ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:93:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if ((await tp.readLine()) === Deno.EOF) {
                                           ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:97:44

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if ((await r.readLine()) === Deno.EOF) {
                                        ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:105:41

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:110:19

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  assert(result != Deno.EOF, "trailer must be set");
                        ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:134:25

TS2339 [ERROR]: Property 'toAsyncIterator' does not exist on type 'typeof Deno'.
  for await (const chunk of Deno.toAsyncIterator(r)) {
                                 ~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.41.0/http/io.ts:167:34

TS2345 [ERROR]: Argument of type 'BufWriter' is not assignable to parameter of type 'Reader'.
  Property 'read' is missing in type 'BufWriter' but required in type 'Reader'.
    const n = await Deno.copy(writer, r.body);
                              ~~~~~~
    at https://deno.land/std@v0.41.0/http/io.ts:276:31

    'read' is declared here.
        read(p: Uint8Array): Promise<number | null>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at $asset$/lib.deno.ns.d.ts:203:5

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
): Promise<ServerRequest | Deno.EOF> {

at https://deno.land/std@v0.41.0/http/io.ts:346:33

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  if (firstLine === Deno.EOF) return Deno.EOF;
                         ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:349:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  if (firstLine === Deno.EOF) return Deno.EOF;
                                          ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:349:43

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  if (headers === Deno.EOF) throw new Deno.errors.UnexpectedEof();
                       ~~~
    at https://deno.land/std@v0.41.0/http/io.ts:351:24

TS2339 [ERROR]: Property 'listenTLS' does not exist on type 'typeof Deno'.
const { listen, listenTLS } = Deno;
                ~~~~~~~~~
    at https://deno.land/std@v0.41.0/http/server.ts:16:17

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    while ((await body.read(buf)) !== Deno.EOF) {}
                                           ~~~
    at https://deno.land/std@v0.41.0/http/server.ts:120:44

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
      let request: ServerRequest | Deno.EOF;
                                        ~~~
    at https://deno.land/std@v0.41.0/http/server.ts:154:41

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (request == Deno.EOF) {
                          ~~~
    at https://deno.land/std@v0.41.0/http/server.ts:170:27

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ListenTLSOptions'.
export type HTTPSOptions = Omit<Deno.ListenTLSOptions, "transport">;
                                     ~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.41.0/http/server.ts:289:38

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ListenTLSOptions'.
  const tlsOptions: Deno.ListenTLSOptions = {
                         ~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.41.0/http/server.ts:309:26

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (rr === Deno.EOF) {
                      ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:85:23

TS2531 [ERROR]: Object is possibly 'null'.
      assert(rr >= 0, "negative read");
             ~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:89:14

TS2531 [ERROR]: Object is possibly 'null'.
      this.w += rr;
                ~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:90:17

TS2531 [ERROR]: Object is possibly 'null'.
      if (rr > 0) {
          ~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:91:11

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async read(p: Uint8Array): Promise<number | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:122:52

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    let rr: number | Deno.EOF = p.byteLength;
                          ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:123:27

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        const nread = rr === Deno.EOF ? 0 : rr;
                                  ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:131:35

TS2531 [ERROR]: Object is possibly 'null'.
        assert(nread >= 0, "negative read");
               ~~~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:132:16

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (rr === 0 || rr === Deno.EOF) return rr;
                                  ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:145:35

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readFull(p: Uint8Array): Promise<Uint8Array | Deno.EOF> {
                                                           ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:172:60

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
        if (rr === Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:177:25

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
            return Deno.EOF;
                        ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:179:25

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readByte(): Promise<number | Deno.EOF> {
                                          ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:194:43

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (this.eof) return Deno.EOF;
                                ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:196:33

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readString(delim: string): Promise<string | Deno.EOF> {
                                                         ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:214:58

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buffer == Deno.EOF) return Deno.EOF;
                       ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:219:24

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buffer == Deno.EOF) return Deno.EOF;
                                        ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:219:41

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readLine(): Promise<ReadLineResult | Deno.EOF> {
                                                  ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:245:51

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
    let line: Uint8Array | Deno.EOF;
                                ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:246:33

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (line === Deno.EOF) {
                      ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:279:23

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:280:19

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readSlice(delim: number): Promise<Uint8Array | Deno.EOF> {
                                                            ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:313:61

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
          return Deno.EOF;
                      ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:330:23

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async peek(n: number): Promise<Uint8Array | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:375:52

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:392:19

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (result === Deno.EOF) {
                        ~~~
    at https://deno.land/std@v0.41.0/io/bufio.ts:551:25

TS2345 [ERROR]: Argument of type '"a"' is not assignable to parameter of type 'OpenOptions | undefined'.
  const file = await open(filepath, "a");
                                    ~~~
    at https://deno.land/std@v0.41.0/io/util.ts:44:37

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
export const isWindows = build.os === "win";
                         ~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.41.0/path/constants.ts:51:26

TS2367 [ERROR]: This condition will always return 'false' since the types '"darwin" | "linux" | "windows"' and '"win"' have no overlap.
const isWin = Deno.build.os === "win";
              ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@v0.41.0/path/globrex.ts:5:15

TS2349 [ERROR]: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
      path = env()[`=${resolvedDevice}`] || cwd();
             ~~~
    at https://deno.land/std@v0.41.0/path/win32.ts:42:14

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
export function assertNotEOF<T extends {}>(val: T | Deno.EOF): T {
                                                         ~~~
    at https://deno.land/std@v0.41.0/testing/asserts.ts:383:58

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
  assertNotEquals(val, Deno.EOF);
                            ~~~
    at https://deno.land/std@v0.41.0/testing/asserts.ts:384:29

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readLine(): Promise<string | Deno.EOF> {
                                          ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:25:43

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (s === Deno.EOF) return Deno.EOF;
                   ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:27:20

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (s === Deno.EOF) return Deno.EOF;
                                    ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:27:37

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readMIMEHeader(): Promise<Headers | Deno.EOF> {
                                                 ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:51:50

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buf === Deno.EOF) {
                     ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:57:22

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      return Deno.EOF;
                  ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:58:19

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
    if (buf === Deno.EOF) {
                     ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:64:22

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (kv === Deno.EOF) throw new Deno.errors.UnexpectedEof();
                      ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:74:23

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'EOF'.
  async readLineSlice(): Promise<Uint8Array | Deno.EOF> {
                                                   ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:115:52

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (r === Deno.EOF) return Deno.EOF;
                     ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:120:22

TS2339 [ERROR]: Property 'EOF' does not exist on type 'typeof Deno'.
      if (r === Deno.EOF) return Deno.EOF;
                                      ~~~
    at https://deno.land/std@v0.41.0/textproto/mod.ts:120:39

Found 72 errors.

**Comment by cindRoberta** [comment] 2020-05-20 05:10
[notecomm@localhost webframeworks]$ deno --version

deno 1.0.0-rc3
v8 8.4.300
typescript 3.8.3

Fedora x86_64

**Comment by zhmushan** [comment] 2020-05-20 05:28
@cindRoberta Please upgrade your deno to 1.0.0

**Comment by cindRoberta** [comment] 2020-05-20 05:40
@zhmushan 

[notecomm@localhost webframeworks]$ deno upgrade

[notecomm@localhost webframeworks]$ curl -fsSL https://deno.land/x/install/install.sh | sh

[notecomm@localhost webframeworks]$ deno --version
deno 1.0.0-rc3
v8 8.4.300
typescript 3.8.3

[notecomm@localhost webframeworks]$ deno run --allow-net server.ts

and same error

**Comment by zhmushan** [comment] 2020-05-20 05:43
@cindRoberta Please try to reinstall deno

**Comment by cindRoberta** [comment] 2020-05-20 05:57
@zhmushan 

[notecomm@localhost webframeworks]$ deno run --allow-net server.ts

Compile file:///home/notecomm/pdeno/webframeworks/server.ts

error: TS7006 [ERROR]: Parameter 'c' implicitly has an 'any' type.
        h = (c) => {
             ^
    at https://deno.land/x/abc/app.ts:39:14

TS7006 [ERROR]: Parameter 'c' implicitly has an 'any' type.
    const h: HandlerFunc = (c) => {
                            ^
    at https://deno.land/x/abc/app.ts:170:29

TS7006 [ERROR]: Parameter 'c' implicitly has an 'any' type.
    return this.get(path, (c) => c.file(filepath), ...m);
                           ^
    at https://deno.land/x/abc/app.ts:180:28

Found 3 errors.

**Comment by zhmushan** [comment] 2020-05-20 06:02
@cindRoberta make sure you are using the latest `abc` (v1.0.0-rc5)

**Comment by cindRoberta** [comment] 2020-05-20 06:10
@zhmushan how I check the version?

**Comment by zhmushan** [comment] 2020-05-20 06:23
@cindRoberta I update the README.md
Deno can import the specified version of the third-party library:
```ts
import { } from "https://deno.land/x/abc@1.0.0-rc5/mod.ts"
```

**Comment by cindRoberta** [comment] 2020-05-20 06:33
@zhmushan the problem was not in the abc, it was in the deno, that needed to be reinstalled manually

sorry for unrelated question but, how I use the json method from the class Context?

**Comment by zhmushan** [comment] 2020-05-20 06:36
@cindRoberta I don't understand what you mean, please describe in detail in a new issue

**Comment by cindRoberta** [comment] 2020-05-20 06:45
to solve this problem just delete the deno binaries on $HOME/.deno/bin/deno and on $HOME/.local/bin and reinstall deno

deno upgrade does not work nor install deno before manual deletion

**Comment by zhmushan** [comment] 2020-05-21 03:21
I now close this issue

**Closed by zhmushan** 2020-05-21 03:21 UTC
